# ./dbt/profiles.yml
my_dez_2025:
  outputs:
    source:
      dbname: "{{ env_var('POSTGRES_DBNAME') }}"
      host: "{{ env_var('POSTGRES_HOST') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') }}"
      schema: dbt
      threads: 4
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
  target: source
