version: '3.8'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase.db
    volumes:
      - metabase_data:/metabase.db
    restart: unless-stopped

volumes:
  metabase_data:
