version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: pg-zoomcamp
    restart: unless-stopped
    environment:
      POSTGRES_USER: zoomcamp
      POSTGRES_PASSWORD: zoomcamp
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
